### ISSUE TITLE
Compatibility with ARM devices / Android

### ISSUE THREAD

**Issue by carlosb1** [hermitcore/libhermit#108]
I am interested to configure libhermit for Android, but I don't know how much effort can be... 
Is somebody working on this? I would interested to know if they are hard dependencies to configure the toolchain for Android (with cmake)... I appreciate any response..

**Comment by stlankes** [comment]
In principle, we support aarch64. My experiences with Android are very low. Personal, I am working with Ubuntu 18.04 on Libre's Le Potato board. Currently, HermitCore is able to run in our KVM-based hypervisor on this board. SMP-support is missing. Other configurations aren't tested. Do you need more information?

**Comment by carlosb1** [comment]
It is enough... thanks!!!
