### ISSUE TITLE
does hermitcore have full support for numa?

### ISSUE THREAD

**Issue by taseikyo** [hermitcore/libhermit#111]
For example, allowing applications to migrate memory from one NUMA node to another

**Comment by stlankes** [comment]
Currently not. I start alway one instance per node. Do you need NUMA support?

**Comment by taseikyo** [comment]
Yes, I need. I want to allocate memory on different nodes, and do some migration experiments. Is it possible?

**Comment by stlankes** [comment]
That is a huge task and takes time. Why do want to use a unikernel instead Linux for such tests?

**Comment by taseikyo** [comment]
OK, thanks for your reply😄
