### ISSUE TITLE
proxy: KVM: receive shutdown command : No such file or directory

### ISSUE THREAD

**Issue by irenge** [hermitcore/libhermit#112]
Hi 
I am a new to hermitux, trying to understand it.

From [https://github.com/ssrg-vt/hermitux](url), I ran all the command successfully except for the last one: 
`sudo HERMIT_ISLE=uhyve HERMIT_TUX=1 \
	../../../hermitux-kernel/prefix/bin/proxy \
	../../../hermitux-kernel/prefix/x86_64-hermit/extra/tests/hermitux \
	../../../musl/prefix/lib/libc.so is-dyn`

that generates 

PIE detected, loading application at 0x400000
proxy: KVM: receive shutdown command
: No such file or directory

Any thing I should be worry about ?
I am running Ubuntu 18
Thanks

[ solved ]

**Comment by irenge** [comment]
it solved

**Comment by yash982000** [comment]
@irenge Can you please provide the solution to this error?

**Comment by stlankes** [comment]
I would say that KVM isn't enabled. Do you have the device `/dev/kvm`on your system?

**Comment by yash982000** [comment]
No, I am yet to set it up.

**Comment by yash982000** [comment]
@stlankes Actually, I have taken this as a project of college. So, I need to solve some issues. Can you help me start with some of them?

**Comment by yash982000** [comment]
@stlankes Also, I wanted to know that can I introduce new issues and create a PR since there is been no change since the past 1 to 1.5 years. Let me know if I can contribute in some or the other way.

**Comment by stlankes** [comment]
Yes, the followup project is hermitcore/rusty-hermit. Here exists currently a compiler issue hermitcore/rusty-hermit#73, we will solve it soon.

**Comment by yash982000** [comment]
@stlankes  I am a bit confused. Is this a part of libhermit? Or this separate to it?

**Comment by yash982000** [comment]
@stlankes I am thinking of adding some new features such as a scheduler algorithm, a virtual memory(paging). Can you open such an issue or can I open such issues.?
Or else we want to work on the issues which are on libhermit itself.

**Comment by jschwe** [comment]
@yash982000 hermitcore/rusty-hermit and https://github.com/hermitcore/libhermit-rs are basically the continuation of hermitcore / libhermit, but the language used is now Rust instead of C. If you are open to working with Rust then I would suggest contributing to rusty-hermit, since it receives active development.
But since this is pretty off-topic from the original Issue, I suggest moving the conversation to slack.

**Comment by yash982000** [comment]
@jschwe Sure, I have joined slack.

**Comment by stlankes** [comment]
Do you want to add these feature in lib hermit-rs?

**Comment by yash982000** [comment]
@stlankes We would love to try, not sure though as not so familiar with rust.
