### ISSUE TITLE
Crash upon hello_proxy execution

### ISSUE THREAD

**Issue by daniel-k** [hermitcore/libhermit#7]
I'm not sure if this intended behaviour, but I suspect that something is still wrong. When I start a proxy example, it looks like something crashes and the linux kernel boots all over again. See output: https://gist.github.com/daniel-k/473aee84ff493f1a41f3

I needed to modify Qemu parameters in order to be able to start it in the first place as my machine has "only" 8GB of RAM.

```
-smp 8 [...] -m 4G -numa node,nodeid=0,cpus=0-3 -numa node,nodeid=1,cpus=4-7
```

and in `linux/arch/x86/hermit/hermit.c` I lowered the pool size to

``` c
static size_t pool_size = 0x10000000ULL;
```

although I don't know yet what this really is. However, it was needed so that HermitCore would initialize successfully and populate `/sys/hermit`.

**Comment by stlankes** [comment]
@youknow0 : Could you check, if the current branch works on your system. I think that I solve the problem.

**Comment by youknow0** [comment]
Yes, it seems to work perfectly now. I’ve tried `/hermit/usr/tests/hello` as well as `/hermit/usr/tests/hello++`. 

For reference: my system is a HP Z600 with a Intel Xeon X5650.
