### ISSUE TITLE
Docker container outdated

### ISSUE THREAD

**Issue by jabocken** [hermitcore/libhermit#88]
It appears the provided Docker container does not provide many of the dependencies needed to build HermitCore as it currently is. It only comes with CMake 3.5.1 despite HermitCore requiring 3.7, and the `local-cmake.sh` script requires Python be installed in the container before it can be run; the hexdump utility is not installed; and there is no detectable C++ compiler.

**Comment by stlankes** [comment]
Sorry, I oversaw this issue. I will update the container...

**Comment by stlankes** [comment]
Hello @jabocken 

excuse me for the delay. Now the docker image based an Ubunutu 18.04. cmake is available in a suitable version. Please note that KVM isn't available in a Docker container. But you could use qemu as hypervisor.

Cheers

Stefan 

> $> HERMIT_ISLE=qemu HERMIT_KVM=0 /opt/hermit/bin/proxy /opt/hermit/x86_64-hermit/extra/tests/hello
Hello World!!!
argv[0] = /opt/hermit/x86_64-hermit/extra/tests/hello
Receive signal with number 30
Hostname: 0b823215b953
$> cmake --version
cmake version 3.10.2

**Comment by stlankes** [comment]
Maybe KVM should work if you start Docker in privilege mode (https://github.com/hermitcore/libhermit/issues/88).

See also https://github.com/sivaramsk/docker-kvm
